### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by robreczarek**
- added missing articles
- added missing prepositions
- added missing punctuation
- handled some stylistic changes

Updated build file output (building = budynek)

QUESTIONS:
What do you mean by "correct type?"
Is "proper type" different from "correct type?"

### CODE REVIEW

**Comment by robreczarek** [comment]
Yeah, I'm checking that command line output too ;)

correct is prawidłowy
proper is właściwy

In my view, it would be better to "use proper."

One more thing. When a sentence ends with a quote, you put punctuation inside the quote. For example:
 Should I change this "correct type" to "proper type?"

It's strange, but correct.

And instead of praise, you would say brag 👍

**Comment by piecioshka** [comment]
@robreczarek thanks!

a) In rev c21713c78587b599a00fc666f504166c6b553e72 I replace "correct" by "proper".
b) about question mark in side quotes - yes it's strange :)
c) "brag", of course, danke!

🖐

**Comment by robreczarek** [comment]
@piecioshka Excellent! 

Almost forgot though. In point number 2 in the QA, you were referring to proper types for variable? I want to be 100% sure, because there may be one change I want to propose.

**Comment by piecioshka** [comment]
Yes, exactly.

**Pull request merged**
